sudo: false
language: ruby
rvm:
  - 2.1.6
  - 2.2.2
  - 2.3.3
  - 2.4.1
  - jruby-9.1.13.0
script:
    - bundle exec rake
    - bundle exec rake test
allow_failures:
    - rvm: jruby-9.1.13.0
bundler_args: --without gui
